# Generated by Django 4.0 on 2021-12-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('IN-TRANSIT', 'in-transit'), ('DELIVERED', 'delivered')], default=('PENDING', 'pending'), max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('SMALL', 'small'), ('MEDIUM', 'medium'), ('LARGE', 'large'), ('EXTRA-LARGE', 'extra-large')], default=('SMALL', 'small'), max_length=20),
        ),
    ]
