# Generated by Django 4.0 on 2021-12-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('HALF', 'half'), ('FULL', 'full')], default=('HALF', 'half'), max_length=20),
        ),
    ]
