# Generated by Django 4.0 on 2022-01-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='types',
            field=models.CharField(choices=[('HYDERABADI-BIRYANI', 'Hyderabadi-Biryani'), ('AMBUR-BIRYANI', 'Ambur-Biryani'), ('MEMONI-BIRYANI', 'Memoni-biryani'), ('THALASSERY-BIRYANI', 'Thalassery-biryani'), ('KASHMIRI-BIRYANI', 'Kashmiri-Biryani'), ('KOLKATA-BIRYANI', 'Kolkata-Biryani')], default=('HALF', 'half'), max_length=20),
        ),
    ]
